coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
# Updated 20251109_123835
# Updated Sun Nov  9 12:49:24 CET 2025
# Updated Sun Nov  9 12:52:39 CET 2025
# Updated Sun Nov  9 12:56:06 CET 2025
