name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/configure-pages@v4
    - name: Create site
      run: |
        mkdir _site
        echo '<h1>vmware-vsan-8-learn</h1><p>Success!</p>' > _site/index.html
    - uses: actions/upload-pages-artifact@v3
    - uses: actions/deploy-pages@v4
